name: Staging pipleline
on:
  push:
    branches:
    - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@v1
  
    - name: Use Node.js
      user: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - name: install dependencies
      run: npm install
